[settings]
input = "~/SureBook/info/def_input.md"
list = "~/SureBook/info/def_lists.md"
topic_save = "~/SureBook/topics"
source_table_file = "~/SureBook/info/src_table.md"
auto_alphabetic_sort = "true"
auto_save = "false"
auto_cast = "true"
auto_cast_format = ""
editor = "nvim"
last_saved = "2026-03-25 21:35:24"
